### ISSUE TITLE
initial conditions not decaying according to dynamics function

### ISSUE THREAD

**Issue by slwu89** [SciML/DelayDiffEq.jl#225]
Hi folks!

In an example for a SIR model implemented as a DDE we observed that the I(t) state variable, which ought to decay to 0 as time -> large, instead decays to I(0), the initial condition (example in this issue https://github.com/epirecipes/sir-julia/issues/49). Is there some way to insist that the initial value of that state variable should also follow the dynamics in the `f` function?

**Comment by ChrisRackauckas** [comment]
Looks like this was solved.
