### ISSUE TITLE
missing cache.alg causing runtime dispatch in LinearSolve

### ISSUE THREAD

**Issue by xzackli** [SciML/DelayDiffEq.jl#235]
There is runtime dispatch happening in LinearSolve.jl, and it's causing a 1.5-2x slowdown for low dimensional problems. I think it's because `linsolve.cache.alg` in DDEIntegrator is never set, so it doesn't take the fast path? This hits the DDEIntegrator every linear solve.

I'm deducing this by setting a breakpoint [here](https://github.com/SciML/LinearSolve.jl/blob/bb1f9f482fc9baf2c2c324cd579eb946f879c19b/src/common.jl#L143).

In this MWE, I disable all lags and don't touch the history, so the DDE should just be stepping for the ODE. I also attach the @profview from a model that actually uses delays.

I'm a little scared to try to fix this myself -- it seems like DelayDiffEq depends in a complicated way on a lot of stuff in OrdinaryDiffEq.

```julia
using OrdinaryDiffEq
using DelayDiffEq 
using BenchmarkTools 

# define an ODE
function bc_model_o(du,u,p,t)
    p0,q0,v0,d0,p1,q1,v1,d1,d2,beta0,beta1,tau = p
    hist3 = 1.0
    du[1] = (v0/(1+beta0*(hist3^2))) * (p0 - q0)*u[1] - d0*u[1]
    du[2] = (v0/(1+beta0*(hist3^2))) * (1 - p0 + q0)*u[1] +
            (v1/(1+beta1*(hist3^2))) * (p1 - q1)*u[2] - d1*u[2]
    du[3] = (v1/(1+beta1*(hist3^2))) * (1 - p1 + q1)*u[2] - d2*u[3]
  end

# wrap it in a DDE
function bc_model(du,u,h,p,t)
    bc_model_o(du, u, p, t)
end

h(p, t; idxs=nothing) = typeof(idxs) <: Number ? 1.0 : ones(3)
tau = 1
lags = ()  # just ignore lags
p0 = 0.2; q0 = 0.3; v0 = 1; d0 = 5
p1 = 0.2; q1 = 0.3; v1 = 1; d1 = 1
d2 = 1; beta0 = 1; beta1 = 1
p = (p0,q0,v0,d0,p1,q1,v1,d1,d2,beta0,beta1,tau)
tspan = (0.0,10.0)
u0 = [1.0,1.0,1.0]

prob1 = ODEProblem(bc_model_o,u0,tspan,p)  # set up ODE/DDE
alg1 = Rodas4()
prob2 = DDEProblem(bc_model,u0,h,tspan,p; constant_lags=lags)
alg2 = MethodOfSteps(alg1)

solve(prob1, alg1,abstol=1e-6,reltol=1e-6)
solve(prob2, alg2,abstol=1e-6,reltol=1e-6)

##
@btime solve($prob1, $alg1,abstol=1e-6,reltol=1e-6);  # ODE: 85 μs
@btime solve($prob2, $alg2,abstol=1e-6,reltol=1e-6);  # DDE: 124 μs

## make a little test function
test(prob, alg) = for i in 1:1000 solve(prob,alg,abstol=1e-10,reltol=1e-10) end

##
@profview test(prob1, alg1)  # ODE looks ordinary
@profview test(prob2, alg2)  # DDE has suspicious GC in the linear solve
```

![image](https://user-images.githubusercontent.com/8048811/182306832-e515af38-7b59-4a83-81fb-8741c79a355c.png)

**Comment by ChrisRackauckas** [comment]
Ahh thanks, this actually has an easy fix. OrdinaryDiffEq.jl resolves this by doing the runtime dispatch once at a high level and then fixing it within the inner loop. That's done in: https://github.com/SciML/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L174 . The fallback of alg preparation is to do nothing, which I guess is what DelayDiffEq ends up doing. But probably a simple dispatch like:

```julia
DiffEqBase.prepare_alg(alg::MethodOfSteps) = MethodOfSteps(DiffEqBase.prepare_alg(alg.alg))
```

i.e. forwarding the method down to the ODE solver choice, is all that's necessary. Then forwarding the arguments from the MethodOfSteps itself of course.

**Comment by ChrisRackauckas** [comment]
See if this helps: https://github.com/SciML/DelayDiffEq.jl/pull/236

**Comment by xzackli** [comment]
The `prepare_alg` signature in #236 needs more args for the initial state vector. 

```julia
DiffEqBase.prepare_alg(alg::MethodOfSteps, u0, p, prob) = MethodOfSteps(
    DiffEqBase.prepare_alg(alg.alg, u0, p, prob); constrained=isconstrained(alg), fpsolve=alg.fpsolve)
```

However, I think there needs to be a definition of `prepare_alg` in DelayDiffEq or some subtyping. The `prepare_alg` in OrdinaryDiffEq still does nothing because it looks for an ODEProblem or an ODEFunction, but we have a DDEProblem and a DDEFunction.

https://github.com/SciML/OrdinaryDiffEq.jl/blob/afd8246e7cdd6bd19a121cb77b2170f1bf19740e/src/alg_utils.jl#L196

**Comment by ChrisRackauckas** [comment]
It's trying to be differentiated from `DAEProblem`, so it should probably just be `prob isa ODEProblem || prob isa DDEProblem`. Try that change and I think it should be good?

**Comment by xzackli** [comment]
Yes! The combination of changes fully resolves the issue by eliminating any dispatch from the linear solve.

**Comment by xzackli** [comment]
This will bring the toy example above from 124 μs to 100 μs. The remaining difference between the DDE above and the identical ODE (83 μs) comes from the DDE having to save_values! twice in the loop_footer.

**Comment by ChrisRackauckas** [comment]
Should be solved now 🎉
