### ISSUE TITLE
MethodError: no method matching OrdinaryDiffEq.InterpolationData

### ISSUE THREAD

**Issue by baggepinnen** [SciML/DelayDiffEq.jl#274]
**Describe the bug 🐞**

Error `MethodError: no method matching OrdinaryDiffEq.InterpolationData` encountered during test of ControlSystems.jl:
https://github.com/JuliaControl/ControlSystems.jl/actions/runs/7180061166/job/19551540208?pr=907#step:6:707

**Minimal Reproducible Example 👇**

[The test that threw the error](https://github.com/JuliaControl/ControlSystems.jl/blob/master/test/test_delay_timeresp.jl#L20)

**Error & Stacktrace ⚠️**

Liked above

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
     Testing ControlSystems
      Status `/tmp/jl_ldIDeQ/Project.toml`
⌅ [4c88cf16] Aqua v0.5.6
  [a6e380b2] ControlSystems v1.10.0 `~/work/ControlSystems.jl/ControlSystems.jl`
  [aaaaaaaa] ControlSystemsBase v1.10.1
  [bcd4f6db] DelayDiffEq v5.43.2
  [459566f4] DiffEqCallbacks v2.34.0
  [e30172f5] Documenter v1.2.1
  [f6369f11] ForwardDiff v0.10.36
  [28b8d3ca] GR v0.72.10
  [e91730f6] Hungarian v0.7.0
  [1dea7af3] OrdinaryDiffEq v6.61.0
  [91a5bcdd] Plots v1.39.0
  [3cdcf5f2] RecipesBase v1.3.4
  [189a3867] Reexport v1.2.2
  [90137ffa] StaticArrays v1.7.0
  [37e2e46d] LinearAlgebra
  [44cfe95a] Pkg v1.9.2
  [de0858da] Printf
  [9a3f8284] Random
  [2f01184e] SparseArrays
  [8dfed614] Test
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

See GH actions log

v1.9 GH actions

**Additional context**

The test or the functionality it tests hasn't been changed in a long time, so some update to DelayDiffEq/DiffEqBase etc. appears to have changed

**Comment by devmotion** [comment]
https://github.com/SciML/OrdinaryDiffEq.jl/pull/2048 broke it (as predicted by @ChrisRackauckas, so the issue is known).

**Comment by ChrisRackauckas** [comment]
Yeah I know...
